bgp_asn: 64519

interfaces:
  - { name: "et-0/0/1", host: "ukabc-prd-spine-01", port: "et-0/0/19", address: "10.0.0.39/31", peer_as: 64591, apply: "GR-INTF-UNDERLAY" }
  - { name: "et-0/0/2", host: "ukabc-prd-spine-02", port: "et-0/0/19", address: "10.0.0.167/31", peer_as: 64592, apply: "GR-INTF-UNDERLAY" }
  - { name: "et-0/0/3", host: "ukabc-prd-spine-03", port: "et-0/0/19", address: "10.0.1.39/31", peer_as: 64593, apply: "GR-INTF-UNDERLAY" }
