interfaces:
  - { name: "et-0/0/1", host: "ukabc-prd-spine-01", port: "et-0/0/5", address: "10.0.0.11/31", apply: "GR-INTF-UNDERLAY" }
  - { name: "et-0/0/2", host: "ukabc-prd-spine-02", port: "et-0/0/5", address: "10.0.0.139/31", apply: "GR-INTF-UNDERLAY" }
  - { name: "et-0/0/3", host: "ukabc-prd-spine-03", port: "et-0/0/5", address: "10.0.1.11/31", apply: "GR-INTF-UNDERLAY" }
