- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: "create local build directory"
      file:
        path: "build/"
        state: directory
      run_once: True

    - name: "include vaulted credentials (global)"
      include_vars: "group_vars/credentials.yml"
      delegate_to: localhost
      failed_when: false
      run_once: true

    - name: "include vaulted credentials (site specific)"
      include_vars: "{{ inventory_dir }}/group_vars/credentials.yml"
      delegate_to: localhost
      failed_when: false
      run_once: true

    - name: "build device configurations"
      template:
        src: "templates/{{ template }}"
        dest: "build/{{ inventory_hostname }}.cfg"
