leaf:
  hosts:
    ukabc-prd-leaf-01:
    ukabc-prd-leaf-02:
    ukabc-prd-leaf-03:
    ukabc-prd-leaf-04:
    ukabc-prd-leaf-05:
    ukabc-prd-leaf-06:
    ukabc-prd-leaf-07:
    ukabc-prd-leaf-08:
    ukabc-prd-leaf-09:
    ukabc-prd-leaf-10:
    ukabc-prd-leaf-11:
    ukabc-prd-leaf-12:
    ukabc-prd-leaf-13:
    ukabc-prd-leaf-14:
    ukabc-prd-leaf-15:
    ukabc-prd-leaf-16:
    ukabc-prd-leaf-17:
    ukabc-prd-leaf-18:
    ukabc-prd-leaf-19:
    ukabc-prd-leaf-20:
    ukabc-prd-leaf-21:
    ukabc-prd-leaf-22:
    ukabc-prd-leaf-23:
    ukabc-prd-leaf-24:
    ukabc-prd-leaf-25:
    ukabc-prd-leaf-26:
    ukabc-prd-leaf-27:
    ukabc-prd-leaf-28:
    ukabc-prd-leaf-29:
    ukabc-prd-leaf-30:
    ukabc-prd-leaf-31:
    ukabc-prd-leaf-32:
spine:
  hosts:
    ukabc-prd-spine-01:
    ukabc-prd-spine-02:
    ukabc-prd-spine-03:
